#!/bin/bash
# Complete Deployment Script for Action Guardrail
# This script deploys backend to Render and frontend to Vercel

echo "=================================================="
echo "Action Guardrail - Complete Deployment Script"
echo "=================================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}STEP 1: Deploy Backend to Render${NC}"
echo "=================================================="
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Select 'Build and deploy from a Git repository'"
echo "4. Click 'Connect Account' and authorize GitHub"
echo "5. Select repository: Action-guardrail"
echo ""
echo "Configuration:"
echo "  - Name: action-guardrail-backend"
echo "  - Environment: Python 3"
echo "  - Build Command: pip install -r requirements.txt"
echo "  - Start Command: uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo "  - Plan: Free tier (or paid for better performance)"
echo ""
echo "Environment Variables (click 'Advanced' → 'Add Environment Variable'):"
echo "  Key: CORS_ORIGINS"
echo "  Value: https://your-vercel-domain.vercel.app"
echo ""
echo "5. Click 'Create Web Service'"
echo "6. Wait for deployment to complete (~2 minutes)"
echo "7. Copy your backend URL (looks like: https://action-guardrail-backend.onrender.com)"
echo ""
read -p "Press Enter when Render backend is deployed and copy the URL above..."

echo ""
echo -e "${YELLOW}STEP 2: Deploy Frontend to Vercel${NC}"
echo "=================================================="
echo ""
echo "1. Go to: https://vercel.com/new"
echo "2. Click 'Select' next to 'Continue with GitHub'"
echo "3. Authorize GitHub if needed"
echo "4. Find and select 'Action-guardrail' repository"
echo "5. Configure project:"
echo "   - Framework Preset: Vite"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: dist"
echo ""
echo "Environment Variables:"
echo "  Key: VITE_API_BASE_URL"
echo "  Value: [PASTE YOUR RENDER BACKEND URL HERE]"
echo ""
echo "6. Click 'Deploy'"
echo "7. Wait for deployment to complete (~3 minutes)"
echo "8. Copy your frontend URL (looks like: https://your-project.vercel.app)"
echo ""
read -p "Press Enter when Vercel frontend is deployed..."

echo ""
echo -e "${YELLOW}STEP 3: Update Backend CORS${NC}"
echo "=================================================="
echo ""
echo "1. Go back to: https://dashboard.render.com"
echo "2. Click on your 'action-guardrail-backend' service"
echo "3. Go to 'Environment' settings"
echo "4. Update CORS_ORIGINS value to:"
echo "   https://[YOUR-VERCEL-DOMAIN].vercel.app"
echo ""
echo "5. Click 'Save' and wait for automatic redeployment"
echo ""
read -p "Press Enter when Render is updated..."

echo ""
echo -e "${GREEN}✓ Deployment Complete!${NC}"
echo "=================================================="
echo ""
echo "Your services are now live:"
echo "  Backend: https://action-guardrail-backend.onrender.com"
echo "  Frontend: https://[YOUR-DOMAIN].vercel.app"
echo ""
echo "To test the connection:"
echo "  1. Open your frontend URL in browser"
echo "  2. Check if the health status shows 'healthy'"
echo "  3. If not, verify CORS_ORIGINS is correctly set on Render"
echo ""
